"""create sessions and messages tables

Revision ID: 5b7739c768fe
Revises: 
Create Date: 2026-09-11 22:22:48.473848

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b7739c768fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('parent_session_id', sa.String(length=36), nullable=True),
    sa.Column('main_session_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('parent_last_seq', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['main_session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', name='uq_sessions_title')
    )
    op.create_index(op.f('ix_sessions_main_session_id'), 'sessions', ['main_session_id'], unique=False)
    op.create_index(op.f('ix_sessions_parent_session_id'), 'sessions', ['parent_session_id'], unique=False)
    op.create_index(op.f('ix_sessions_title'), 'sessions', ['title'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=255), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role <> 'tool' OR (tool_call_id IS NOT NULL AND tool_call_id <> '')", name='ck_messages_tool_requires_call_id'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'seq', name='uq_messages_session_seq')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index('ix_messages_session_seq', 'messages', ['session_id', 'seq'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_session_seq', table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_title'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_parent_session_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_main_session_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
